// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PoleEmploiApp.DataEntities
{
    public partial class JobOffer
    {
        public int Id { get; set; }
        public string PoleEmploiId { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string ContractType { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime LastModificationDate { get; set; }
        public string CompanyName { get; set; }
        public string DescriptionLocation { get; set; }
        public string WorkTime { get; set; }
        public string CityCode { get; set; }
        public string ApplicationUrl { get; set; }
    }
}