// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PoleEmploiApp.DataEntities
{
    public partial class PoleEmploiContext : DbContext
    {
        public PoleEmploiContext()
        {
        }

        public PoleEmploiContext(DbContextOptions<PoleEmploiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<JobOffer> JobOffers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<JobOffer>(entity =>
            {
                entity.ToTable("JobOffer");

                entity.Property(e => e.ApplicationUrl).HasMaxLength(256);

                entity.Property(e => e.CityCode).HasMaxLength(10);

                entity.Property(e => e.CompanyName).HasMaxLength(500);

                entity.Property(e => e.ContractType).HasMaxLength(256);

                entity.Property(e => e.CreationDate).HasColumnType("datetime");

                entity.Property(e => e.DescriptionLocation).HasMaxLength(500);

                entity.Property(e => e.LastModificationDate).HasColumnType("datetime");

                entity.Property(e => e.PoleEmploiId)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.Title).HasMaxLength(500);

                entity.Property(e => e.WorkTime).HasMaxLength(256);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}